from __future__ import annotations

MELODY_TUNETA_BASE_VELOCITY = 0.02
MELODY_BASE_VELOCITY = 0.4
MELODY_CHORUS_BASE_VELOCITY = 0.05

BASS_BASE_VELOCITY = 0.4
GUITAR_BASE_VELOCITY = 0.10
DRUM_BASE_VELOCITY = 0.2
